// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqyskwhvzciuzlmsgjfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxeXNrd2h2emNpdXpsbXNnamZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTE0OTEsImV4cCI6MjA2NTQ4NzQ5MX0.inp9AzBB52krx2GjJwYkPrUEld6kFoM0eaHaKWlFrt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);